name: AI Agentic Pull Request

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    # Allow manual triggering
  push:
    branches:
      - main
    paths:
      - 'ai-agent/**'

jobs:
  ai-analysis:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pull-requests: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: Run AI Agent Analysis
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        python3 ai-agent/scripts/agent.py ai-agent/config/agent-config.yaml > analysis-results.json
        
    - name: Display Analysis Results
      run: |
        echo "## AI Agent Analysis Results" >> $GITHUB_STEP_SUMMARY
        echo '```json' >> $GITHUB_STEP_SUMMARY
        cat analysis-results.json >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        
    - name: Upload Analysis Results
      uses: actions/upload-artifact@v3
      with:
        name: ai-analysis-results
        path: analysis-results.json
        retention-days: 30